[package]
name = "balls"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8.4"
interprocess = "2.2.1"
rand = "0.8.5"
rapier2d ={ version = "0.22.0", features = [ "simd-stable", "parallel", "serde-serialize"] }
raylib = "5.0.1"
